### ISSUE TITLE
No longer working? Rick Roll every time.

### ISSUE THREAD

**Issue by jefferose** [BenSampo/laravel-embed#10]
It could be that I'm running locally, I guess, but no matter what video I try to embed it comes up as a Rick Roll.

Did YouTube change their setup or am I doing something wrong?

**Comment by BenSampo** [comment]
Ha, it's certainly not supposed to do that.

It sounds like your views might be cached and it's stuck on the version you copied from the docs. Try running `php artisan view:clear` and see if that helps.

**Comment by jefferose** [comment]
User error. You were right, I copied the x-embed line and didn't paste in my variable. Sorry.

**Comment by BenSampo** [comment]
Excellent, so you deserved the rick roll :) Glad you got it sorted
