### ISSUE TITLE
Idea: Any way to hide youtube / vimeo controls?

### ISSUE THREAD

**Issue by stuartcusackie** [BenSampo/laravel-embed#8]
Cool package! Just wondering if you've thought about adding options to hide youtube related videos, logos and other controls from various providers.

Thanks for this package!

**Comment by peacenation** [comment]
Cool plugin, have you thought of incorporating Youtube Chat and also Chrome Cast Button on the player

**Comment by BenSampo** [comment]
Feel free to submit PR's for these...
